name: Build

on:
  workflow_dispatch:
  #workflow_run:
  #  workflows: ["Python Syntax Check"]
  #  types:
  #    - completed
#on: [push]
#on:
 # release:
  #  types: [published]
jobs:
  build-android:
    # ⛔️ This line ensures it only runs if the syntax check succeeded
   # if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # used to cache dependencies with a timeout
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('mobile/buildozer.spec') }}

      - uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('mobile/buildozer.spec') }}

      - name: Build with Buildozer
        uses: n8marti/buildozer-action@fix-user-doesnt-exist
        id: buildozer
        with:
          workdir: mobile
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
